### ISSUE TITLE
Duplicate line does not work if last line

### ISSUE THREAD

**Issue by poacher2k** [nick/duplicate-line-or-selection#4]
Hey!

Thank you for the great work with this plugin - it has really helped making the transition from ST2 to Atom being smooth.

**Issue**
Duplicating the last line in a file inserts the duplicated line on the current line, so instead of ending up with:

```
Last line!
Last line!
```

you end up with:
`Last line!Last line!`

**Comment by poacher2k** [comment]
Hi!
Adding

```
if selection.isEmpty()
  textToDuplicate = textToDuplicate + '\n' if endRow == editor.getLastBufferRow()
```

Seems to solve the problem for me.

**Comment by nick** [comment]
Nice! Can you submit a pull request and I'll get it merged
