### ISSUE TITLE
Duplicate line is duplicating twice

### ISSUE THREAD

**Issue by ricardofreeman** [nick/duplicate-line-or-selection#7]
Hi Nick,
After the latest update, when I hit Ctrl-Shift-D I get the same line 3 times instead of only 2 as supposed.
Is this a new bug?
Thanks in advance.

**Comment by nick** [comment]
Can you try restarting Atom? I had the same issue but restarting atom seemed to fix it.

**Comment by ricardofreeman** [comment]
Yes after restarting the editor it got fixed, sorry for posting this issue.
Thank you!
