### ISSUE TITLE
Last update introduced a new bug when duplicating lines

### ISSUE THREAD

**Issue by poacher2k** [nick/duplicate-line-or-selection#8]
Hi!

When attempting to duplicate multiple lines, it creates an extra duplication on each line. This was not present in v0.5.0

Before duplication
![image](https://cloud.githubusercontent.com/assets/2255960/19417085/b0fdffe6-93a3-11e6-9f0d-60627929c4c5.png)
After
![image](https://cloud.githubusercontent.com/assets/2255960/19417091/c7876d06-93a3-11e6-926f-f78230fd555a.png)

Update:
Seems this also happens with single lines
![image](https://cloud.githubusercontent.com/assets/2255960/19417182/935c05b6-93a6-11e6-8e60-09cb0b4dbfd7.png)
![image](https://cloud.githubusercontent.com/assets/2255960/19417184/a5981f12-93a6-11e6-84dd-bc2df388607e.png)

**Comment by nick** [comment]
Please can you try restarting atom?

**Comment by poacher2k** [comment]
I've confirmed this happens on 3 different installs of Atom across both Linux and Windows. Restarting does not seem to do anything.

Can it be a config error? Seems unlikely though. It works when I replace the code with a previous version.

**Comment by jpillora** [comment]
I had this issue though a restart seems to have fixed it.

My `keymap.cson` looks like:

```
# Your keymap
'atom-text-editor':
  'ctrl-d': 'duplicate-line-or-selection:duplicate'
```
